### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by tom-knight** [lihop/godot-pixelmatch#3]
Hi,

I've started working on getting godot-pixelmatch working with Godot 4 on my [fork](https://github.com/tom-knight/godot-pixelmatch/tree/godot4), I've got the main script working but need to check the tests and docs.

Once I've got it ready I'll submit a PR.

Other add-ons I've seen use a different branch and have two entries in the Asset Lib if the code is incompatible between versions 3.x and 4.x.

**Comment by lihop** [comment]
Hi @tom-knight,

Thanks for opening this issue.

I've cherry-picked the godot 4 commit from your fork and added some additional changes for tests and docs, so the main branch now supports Godot 4.

The Godot 3 code now lives in the [godot-3.x branch](https://github.com/lihop/godot-pixelmatch/tree/godot-3.x).
